CONFIG_TICK_ZEPHLET=y
CONFIG_UI_ZEPHLET=y
# CONFIG_TAMPER_DETECTION_ZEPHLET=y
CONFIG_BATTERY_ZEPHLET=y
CONFIG_STORAGE_ZEPHLET=y

CONFIG_LOG=y
CONFIG_ADAPTERS_LOG_LEVEL_DBG=y
CONFIG_TICK_ZEPHLET_LOG_LEVEL_DBG=y
CONFIG_STORAGE_ZEPHLET_LOG_LEVEL_DBG=y
CONFIG_UI_ZEPHLET_LOG_LEVEL_DBG=y
# CONFIG_TAMPER_DETECTION_ZEPHLET_LOG_LEVEL_DBG=y
CONFIG_BATTERY_ZEPHLET_LOG_LEVEL_DBG=y

CONFIG_ASSERT=y
