CONFIG_ZEPHLETS_COAP=y
CONFIG_COAP_SERVER_WELL_KNOWN_CORE=y

CONFIG_COAP=y
CONFIG_COAP_SERVER=y
CONFIG_COAP_URI_WILDCARD=y
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y

CONFIG_MAIN_STACK_SIZE=2048
